export const SITE_URL = "https://brunofzn.dev"
export const SITE_NAME = "Bruno Silva - Web Developer"
export const AUTHOR = "Bruno Rodrigues e Silva"
export const DOMAIN = "brunofzn.dev"
export const OPENGRAPH_IMAGE = "./opengraph-image.jpg"
export const SOURCECODE = "https://github.com/bruno-rodrigues0/brunofzn.dev"
